/**
 * The public demo film (brief §18).
 *
 * "FRAME Demo Film" exists so someone can see what FRAME actually is before
 * signing up for anything. It is a complete worked example — story, vision,
 * Visual DNA, world bible, scenes, shots and composed prompts — so the
 * pipeline the landing page describes can be walked end to end.
 *
 * Two properties matter:
 *
 *   · No API key is needed to explore it. Every prompt below is produced by
 *     the deterministic prompt engine from this material; nothing here was
 *     generated by a model and nothing here calls one.
 *
 *   · It is read-only for everyone. `is_demo = 1`, and `access.mjs` refuses
 *     every write against it, so no visitor can spoil it for the next.
 *
 * Seeding is idempotent: the film is created once and then left alone, so a
 * redeploy never duplicates it or overwrites edits made to the seed by hand.
 */
import { all, one, insert, uid, now } from './db.mjs'
import { composePrompt } from './prompt-engine.mjs'

export const DEMO_NAME = 'FRAME Demo Film'

const CHARACTERS = [
  {
    name: 'Tomas',
    age: 'late sixties', gender: 'male',
    appearance: 'tall, narrow through the shoulders, stooped from decades of low doorways',
    face: 'deep vertical lines, grey stubble, pale eyes that do not settle',
    hair: 'white, cropped close, thinning at the crown',
    clothing: 'oiled canvas work coat over a collarless shirt, both the colour of wet stone',
    body_type: 'lean, hands disproportionately large',
    distinctive: 'a burn scar across the back of the right hand, old and silvered',
    personality: 'patient to the point of obstinacy; speaks only when the answer is short',
    performance: 'stillness over gesture — he is a man who waits for rooms to settle',
    continuity: 'the coat stays on indoors; he never rolls his sleeves past the scar',
  },
  {
    name: 'Ilse',
    age: 'thirty-one', gender: 'female',
    appearance: 'compact, quick, always slightly ahead of where she was a second ago',
    face: 'broad cheekbones, a habit of pressing her lips flat when she is thinking',
    hair: 'dark, cut at the jaw, tucked behind one ear',
    clothing: 'a city overcoat that is wrong for the weather, good shoes ruined by the yard',
    body_type: 'small-framed',
    distinctive: 'she carries her father’s notebook in an inside pocket and touches it often',
    personality: 'impatient with sentiment, and privately full of it',
    performance: 'listen for what she does not say when Tomas is speaking',
    continuity: 'the overcoat is never buttoned; the notebook never leaves the inside pocket',
  },
]

const LOCATIONS = [
  {
    name: 'The Still House',
    architecture: 'a long stone shed, roof trusses black with a century of smoke, one clerestory window per bay',
    geography: 'set into a north-facing slope above the village, half-buried on the uphill side',
    materials: 'granite block, cast iron, unpainted copper gone green at every seam',
    colors: 'wet grey, verdigris, the dull orange of rust bloom',
    weather: 'cold enough indoors to see breath until the fire is lit',
    time_characteristics: 'light enters in single shafts and moves visibly across the floor',
    lighting: 'one shaft of window light per bay; everything else falls to shadow',
    atmosphere: 'still, mineral, faintly sweet from twenty years of absorbed spirit',
  },
  {
    name: 'The Yard',
    architecture: 'cobbled, sloped to a central drain, a low wall on the valley side',
    geography: 'the shelf of flat ground between the still house and the drop to the village',
    materials: 'wet cobble, lichen, a stack of rotted cask staves',
    colors: 'slate, moss green, the white of a sky with no sun in it',
    weather: 'a standing drizzle that never quite becomes rain',
    time_characteristics: 'the light is flat and directionless all day',
    lighting: 'overcast, shadowless',
    atmosphere: 'exposed, wind off the valley, the village audible but not visible',
  },
]

const PROPS = [
  {
    name: 'The Notebook',
    description: 'a pocket ledger, spine broken, swollen to twice its bound thickness',
    material: 'pressed board covers, cotton paper, a cloth spine gone to threads',
    color: 'oxblood, faded to brown at the corners',
    age: 'forty years',
    condition: 'water-marked along the bottom edge; the last third is unwritten',
    dimensions: 'fits a coat pocket, roughly 90 by 140mm',
  },
  {
    name: 'The Spirit Safe',
    description: 'a brass and glass box on the still’s outflow, padlocked, its dials at zero',
    material: 'brass, plate glass, a steel hasp',
    color: 'brass gone brown, glass clouded from the inside',
    age: 'original to the building',
    condition: 'sound, but the lock has rusted shut and the key is long gone',
    dimensions: 'the size of a small suitcase, mounted at chest height',
  },
]

const SCENES = [
  {
    title: 'Cold Iron',
    location: 'The Still House',
    time_of_day: 'dawn',
    duration: '45s',
    story_purpose: 'Establish the still house as abandoned, and Tomas as the only one who still comes here.',
    emotional_purpose: 'Dormancy. Something large and capable, switched off.',
    description:
      'Tomas lets himself into the still house before the light is up. He walks the length of it without ' +
      'turning anything on, stopping once at the spirit safe to look at the dials. He does not touch them. ' +
      'The stills are cold. His breath shows.',
    dna: { color: 'desaturated toward grey-green, copper the only warmth', lighting: 'pre-dawn, one window per bay', atmosphere: 'suspended, mineral-cold' },
    shots: [
      {
        title: 'The door, from inside',
        duration: '6s',
        purpose: 'Enter the space with him, so the room is revealed at his pace rather than ours.',
        description: 'The still house in the dark. The door opens at the far end and Tomas is a shape against a grey rectangle.',
        subject_primary: 'Tomas',
        action: 'pushes the door, waits on the threshold, steps through',
        expression: 'unreadable, backlit',
        shot_type: 'wide', lens: '35mm', camera_height: 'eye level', camera_angle: 'level',
        camera_movement: 'static', depth_of_field: 'deep', framing: 'symmetrical, door centred at the end of the bay',
        composition: 'the length of the building as a corridor of shadow',
        light_source: 'the open door', light_direction: 'dead backlight', light_quality: 'hard-edged',
        color_temp: 'cold blue-grey', light_contrast: 'extreme, near silhouette',
        time_of_day: 'dawn', atmosphere: 'dust visible in the doorway light',
        subject_motion: 'slow walk-in', camera_motion: 'none', env_motion: 'dust',
        emotion: 'dormancy', energy: 'very low', pacing: 'held',
        entities: ['Tomas', 'The Still House'],
      },
      {
        title: 'Hands on the safe',
        duration: '5s',
        purpose: 'The scar, the lock and the refusal to touch, in one frame.',
        description: 'Tomas stops at the spirit safe. His hand comes up, hovers at the glass, and goes back into his pocket.',
        subject_primary: 'Tomas', subject_secondary: 'The Spirit Safe',
        action: 'raises his right hand toward the glass, does not make contact, withdraws',
        expression: 'off-frame; the hand carries it',
        shot_type: 'insert', lens: '85mm', camera_height: 'chest', camera_angle: 'level',
        camera_movement: 'static', depth_of_field: 'shallow', framing: 'hand and brass filling frame',
        composition: 'the scar in focus, the clouded glass behind it soft',
        light_source: 'clerestory window', light_direction: 'three-quarter side', light_quality: 'soft',
        color_temp: 'neutral cold', light_contrast: 'moderate',
        atmosphere: 'still air',
        subject_motion: 'the hand only', camera_motion: 'none', env_motion: 'none',
        emotion: 'restraint', energy: 'low', pacing: 'held',
        entities: ['Tomas', 'The Spirit Safe'],
      },
    ],
  },
  {
    title: 'What the Notebook Says',
    location: 'The Yard',
    time_of_day: 'day',
    duration: '60s',
    story_purpose: 'Ilse arrives with the notebook and the two of them discover the handwriting is not her father’s.',
    emotional_purpose: 'The ground moves. Neither of them says so.',
    description:
      'Ilse comes up from the village in the wrong coat. She gets the notebook out in the drizzle and holds it ' +
      'open for Tomas rather than handing it over. He reads two lines and stops. The silence afterwards is the scene.',
    dna: { color: 'flat slate and moss, the oxblood notebook the only saturated thing', lighting: 'overcast, shadowless', atmosphere: 'exposed, wet' },
    shots: [
      {
        title: 'Up from the village',
        duration: '8s',
        purpose: 'She is out of place here, and she knows it.',
        description: 'Ilse climbs the last of the track into the yard, shoes wrong, coat open, one hand at her chest holding the pocket shut.',
        subject_primary: 'Ilse',
        action: 'climbs into frame, stops, looks at the still house rather than at Tomas',
        expression: 'braced',
        shot_type: 'medium wide', lens: '50mm', camera_height: 'eye level', camera_angle: 'level',
        camera_movement: 'static', depth_of_field: 'medium', framing: 'she enters low frame-right, the valley behind her',
        composition: 'the drop to the village as negative space on her right',
        light_source: 'overcast sky', light_direction: 'omnidirectional', light_quality: 'flat and soft',
        color_temp: 'cold neutral', light_contrast: 'very low',
        weather: 'standing drizzle', time_of_day: 'day', atmosphere: 'wind off the valley',
        subject_motion: 'walking, slowing', camera_motion: 'none', env_motion: 'drizzle, coat moving in wind',
        emotion: 'trespass', energy: 'contained', pacing: 'even',
        entities: ['Ilse', 'The Yard'],
      },
      {
        title: 'Two lines',
        duration: '7s',
        purpose: 'The discovery, played entirely on a face that refuses to give it.',
        description: 'Tomas reads. He gets two lines in and his eyes stop moving. He does not look up.',
        subject_primary: 'Tomas', subject_secondary: 'The Notebook',
        action: 'reads, stops, holds absolutely still',
        expression: 'the moment the eyes stop tracking',
        shot_type: 'close-up', lens: '85mm', camera_height: 'eye level', camera_angle: 'slightly low',
        camera_movement: 'static', depth_of_field: 'shallow', framing: 'tight, notebook edge in bottom frame',
        composition: 'his eyes on the upper third, the page a soft red mass below',
        light_source: 'overcast sky', light_direction: 'top-flat', light_quality: 'soft',
        color_temp: 'cold neutral', light_contrast: 'low',
        weather: 'drizzle on the lens side of frame', atmosphere: 'wet',
        subject_motion: 'none — the stillness is the performance', camera_motion: 'none', env_motion: 'fine rain',
        emotion: 'the floor going', energy: 'held breath', pacing: 'suspended',
        entities: ['Tomas', 'Ilse', 'The Notebook'],
      },
    ],
  },
]

/**
 * Create the demo film if it is not already there.
 *
 * Returns the project id either way, so the landing page always has something
 * to link to. Every failure is swallowed and logged: a demo that cannot be
 * seeded is a missing sample, not a reason for the server not to start.
 */
export async function ensureDemoProject() {
  const existing = await one('SELECT id FROM projects WHERE is_demo = 1')
  if (existing) return existing.id

  const ts = now()
  const projectId = uid()

  await insert('projects', {
    id: projectId,
    owner_id: null,
    is_demo: 1,
    name: DEMO_NAME,
    format: 'cinematic short',
    status: 'Creative Development',
    logline: 'A man who stopped a distillery twenty years ago is handed a notebook in handwriting he does not recognise.',
    core_emotion: 'the quiet after something is found out',
    created_at: ts, updated_at: ts,
  })

  await insert('idea', {
    project_id: projectId,
    raw_text:
      'A distillery above a village, cold for twenty years. The man who stopped it still walks the floor every ' +
      'morning and touches nothing. His partner’s daughter comes back with her father’s notebook and the ' +
      'handwriting in it is not her father’s. I want the whole film to feel like the minute before someone ' +
      'decides to say something. Copper, wet stone, one shaft of light per bay.',
    updated_at: ts,
  })

  await insert('story', {
    project_id: projectId,
    premise: 'Two people discover that the reason a distillery closed was never the reason they were told.',
    logline: 'A man who stopped a distillery twenty years ago is handed a notebook in handwriting he does not recognise.',
    beginning: 'Tomas opens the still house before dawn, as he has every morning for twenty years, and turns nothing on.',
    middle: 'Ilse arrives from the city with her late father’s notebook. Tomas reads two lines and stops.\n\n'
      + 'Neither of them says what they have both understood. They stand in the yard in the rain instead.',
    ending: 'Tomas lights the fire under the wash still for the first time in twenty years. Ilse watches and does not ask why.',
    characters: 'Tomas, who stopped it. Ilse, who was told a story about why.',
    conflict: 'The truth is available to both of them and neither will be the one to say it aloud.',
    theme: 'What it costs to keep someone else’s secret past their death.',
    emotional_journey: 'dormancy → trespass → the floor going → a decision made without discussion',
    message: 'Some things are restarted rather than explained.',
    visual_motifs: 'cold copper, single shafts of window light, the unopened spirit safe, rain that never becomes weather',
    updated_at: ts,
  })

  await insert('director_vision', {
    project_id: projectId,
    genre: 'quiet drama',
    tone: 'restrained, mineral, unsentimental',
    emotional_journey: 'Start dormant. Let one discovery move the floor. End on an action, not a line.',
    pacing: 'Slow, but never idle. Every held frame is held because something is being decided in it.',
    camera_philosophy:
      'Locked off unless a move is motivated by a character. The camera waits; it does not hunt. '
      + 'Wides for the building, long lenses for faces, nothing in between.',
    performance_direction: 'Under. Always under. The scene is what they decline to say.',
    editing_philosophy: 'Cut late. Let shots outstay their information by a beat.',
    locked: 0,
    updated_at: ts,
  })

  await insert('visual_dna', {
    id: uid(), project_id: projectId, version: 1, is_current: 1, locked: 0, label: 'Initial',
    film_character: 'photochemical, fine grain, slight halation in the highlights',
    color: 'desaturated slate and moss, with copper and oxblood as the only warm values',
    contrast: 'low-contrast mids, protected highlights, shadows that go genuinely black',
    texture: 'wet stone, oxidised metal, cotton paper',
    lighting: 'single-source and directional indoors; flat overcast outdoors. Never a fill you can name.',
    atmosphere: 'cold air made visible — breath, dust, fine rain',
    camera: 'static frames, 35mm for space and 85mm for faces, no zooms',
    depth: 'deep for the building, shallow for hands and faces',
    image_quality: 'anamorphic softness at the edges, sharp centre',
    avoid: 'warm fill light, lens flare, drone shots, colour grading toward teal and orange, visible camera shake',
    created_at: ts, updated_at: ts,
  })

  /* ----------------------- world bible ----------------------- */
  const entityIds = new Map()
  const seedEntities = async (table, rows, kind) => {
    for (const [i, row] of rows.entries()) {
      const id = uid()
      await insert(table, { id, project_id: projectId, sort: i + 1, locked: 0, updated_at: ts, ...row })
      entityIds.set(row.name, { kind, id })
    }
  }
  await seedEntities('characters', CHARACTERS, 'character')
  await seedEntities('locations', LOCATIONS, 'location')
  await seedEntities('props', PROPS, 'prop')

  /* -------------------- scenes, shots, prompts -------------------- */
  let shotNumber = 0
  for (const [sceneIndex, sceneSpec] of SCENES.entries()) {
    const sceneId = uid()
    const location = entityIds.get(sceneSpec.location)
    await insert('scenes', {
      id: sceneId, project_id: projectId,
      number: sceneIndex + 1, sort: sceneIndex + 1,
      title: sceneSpec.title,
      location_id: location?.id ?? null,
      location_text: sceneSpec.location,
      time_of_day: sceneSpec.time_of_day,
      duration: sceneSpec.duration,
      story_purpose: sceneSpec.story_purpose,
      emotional_purpose: sceneSpec.emotional_purpose,
      description: sceneSpec.description,
      updated_at: ts,
    })
    await insert('scene_dna', {
      scene_id: sceneId, mode: 'extend', locked: 0, updated_at: ts, ...sceneSpec.dna,
    })
    if (location) {
      await insert('entity_links', {
        id: uid(), owner_type: 'scene', owner_id: sceneId,
        entity_type: 'location', entity_id: location.id,
      })
    }

    for (const [shotIndex, shotSpec] of sceneSpec.shots.entries()) {
      const { entities, ...fields } = shotSpec
      const shotId = uid()
      await insert('shots', {
        id: shotId, project_id: projectId, scene_id: sceneId,
        number: ++shotNumber, sort: shotIndex + 1,
        status: 'draft', updated_at: ts, ...fields,
      })
      for (const name of entities ?? []) {
        const hit = entityIds.get(name)
        if (!hit) continue
        await insert('entity_links', {
          id: uid(), owner_type: 'shot', owner_id: shotId,
          entity_type: hit.kind, entity_id: hit.id,
        })
      }
    }
  }

  // Compose a prompt for every shot, so the Prompt Lab has something to show
  // on arrival. This is the deterministic engine — no model is involved.
  await composeDemoPrompts(projectId, ts)

  return projectId
}

/** Build and store the current prompt for every demo shot. */
async function composeDemoPrompts(projectId, ts) {
  const project = await one('SELECT * FROM projects WHERE id = ?', projectId)
  const vision = await one('SELECT * FROM director_vision WHERE project_id = ?', projectId)
  const dna = await one('SELECT * FROM visual_dna WHERE project_id = ? AND is_current = 1', projectId)
  const shots = await all('SELECT * FROM shots WHERE project_id = ? ORDER BY sort', projectId)

  for (const shot of shots) {
    const scene = await one('SELECT * FROM scenes WHERE id = ?', shot.scene_id)
    const sceneDna = await one('SELECT * FROM scene_dna WHERE scene_id = ?', shot.scene_id)
    const links = await all(
      'SELECT * FROM entity_links WHERE owner_type = ? AND owner_id = ?', 'shot', shot.id)

    const pick = async (kind, table) => {
      const rows = await Promise.all(links.filter((l) => l.entity_type === kind)
        .map((l) => one(`SELECT * FROM ${table} WHERE id = ?`, l.entity_id)))
      return rows.filter(Boolean)
    }
    const locations = await pick('location', 'locations')
    if (!locations.length && scene?.location_id) {
      const l = await one('SELECT * FROM locations WHERE id = ?', scene.location_id)
      if (l) locations.push(l)
    }

    const built = composePrompt({
      project, vision, dna, scene, sceneDna, shot,
      characters: await pick('character', 'characters'),
      locations,
      props: await pick('prop', 'props'),
    })

    await insert('prompts', {
      id: uid(), shot_id: shot.id, version: 1, is_current: 1,
      body: built.body, negative: built.negative,
      layers_json: JSON.stringify(built.layers ?? []),
      hand_edited: 0, created_at: ts,
    })
  }
}
